"""Write engine/assets.js — the asset manifest the page reads (window.__ASSETS__).

Why this exists: the engine runs from file://, where Chromium blocks fetch/XHR of local JSON, and a
missing <img> logs a console error that makes render.py exit with code 2. So the page never probes
the disk itself; this script checks what exists and inlines assets/sprites/anims.json.

Run it (from 制作/) whenever the sprites or backgrounds change, before rendering:
    python engine/sync_assets.py
Missing pieces fall back to placeholders in the page (grey sprite block / dark gradient background).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITES = ROOT / "assets" / "sprites"
BG = ROOT / "assets" / "bg"
OUT = Path(__file__).resolve().parent / "assets.js"

REQUIRED_ANIMS = ["idle_m0", "idle_m1", "idle_m2", "reach_m0", "reach_m1", "reach_m2", "walk"]


def load_anims():
    p = SPRITES / "anims.json"
    if not p.exists():
        return None, "assets/sprites/anims.json not found"
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        return None, f"anims.json unreadable: {e}"
    anims = data.get("anims") or {}
    missing = [a for a in REQUIRED_ANIMS if a not in anims]
    if missing:
        return None, f"anims.json lacks {missing}"
    for name, a in anims.items():
        frames = a.get("frames") or []
        durs = a.get("durations") or []
        if not frames or len(frames) != len(durs):
            return None, f"anim {name}: frames/durations mismatch"
        for f in frames:
            if not (SPRITES / f).exists():
                return None, f"anim {name}: missing frame {f}"
    return data, f"ok ({len(anims)} anims)"


def main():
    anims, msg_a = load_anims()
    # assets/bg/episode.png, when present, is the single background for the whole episode (every scene);
    # otherwise each scene uses bg1 / bg2 as set in timeline.json.
    single = BG / "episode.png"
    if single.exists():
        bg = {"bg1": True, "bg2": True}
        paths = {"bg1": "../assets/bg/episode.png", "bg2": "../assets/bg/episode.png"}
    else:
        bg = {k: (BG / f"{k}.png").exists() for k in ("bg1", "bg2")}
        paths = {k: (f"../assets/bg/{k}.png" if v else None) for k, v in bg.items()}
    manifest = {
        "anims": anims,
        "spriteBase": "../assets/sprites/",
        "bg": paths,
    }
    if single.exists():
        # the episode artwork is bright pastel: dim and soften it more so cards and subtitles stay dominant
        manifest.update(bgAlpha=0.30, bgBlur=9)
    OUT.write_text(
        "// generated by engine/sync_assets.py — do not edit by hand\n"
        f"window.__ASSETS__ = {json.dumps(manifest, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"sprites: {msg_a}")
    print(f"bg: {bg}")
    print(f"-> {OUT}")


if __name__ == "__main__":
    main()
